[package]
name = "rosella-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.34.0"
ash-window = "0.8.0"
gpu-allocator = "0.12.0"
log = "0.4.14"
topological-sort = "0.1.0"
shaderc = "0.7.3"
nalgebra = "0.29.0"
paste = "1.0.6"
winit = "0.25.0"
xxhash-rust = { version="0.8.2", features=["xxh3", "const_xxh3"] }

[dev-dependencies]
env_logger = "0.9.0"