[package]
name = "rosella-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = {  }
ash-window = {  }
winit = { version = "0.25.0" }
topological-sort = { version = "0.1.0" }
shaderc = "0.7.3"
nalgebra = "0.29.0"
xxhash-rust = { features=["xxh3", "const_xxh3"] }
